const $=s=>document.querySelector(s);let DATA=[],FILTER='all';const b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const eur=n=>'€'+Math.round(n/1000)+'k';
async function unlock(){const p=$('#pass').value.trim();if(!p)return;$('#lockmsg').textContent='Decrypting 300 applications…';try{const env=await fetch('encrypted.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('dataset missing');return r.json()});const km=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(env.salt),iterations:env.iterations,hash:'SHA-256'},km,{name:'AES-GCM',length:256},false,['decrypt']);const raw=b64(env.data),tag=b64(env.tag),all=new Uint8Array(raw.length+tag.length);all.set(raw);all.set(tag,raw.length);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(env.iv),tagLength:128},key,all);const obj=JSON.parse(new TextDecoder().decode(plain));DATA=obj.applications.map(enrich);$('#lock').classList.add('hidden');$('#app').classList.remove('hidden');render()}catch(e){console.error(e);$('#lockmsg').textContent='Wrong passphrase or dataset unavailable.'}}
function classify(role=''){const s=role.toLowerCase();if(/qa|tester|quality assurance/.test(s))return'QA / Testing';if(/trust|moderator|safety/.test(s))return'Trust & Safety';if(/customer success engineer|technical support|helpdesk|technical assistant|support engineer/.test(s))return'Technical Support';if(/customer success|customer support|customer service|community support|onboarding/.test(s))return'Customer Success / Support';if(/revenue operations|sales operations|operations|assistant|admin|billing|payment|inventory|recruitment|bookkeeping|product & ops|fulfilment/.test(s))return'Operations / Data';if(/account executive|sales|business development|sdr|partnership|lead generation/.test(s))return'Sales / BD';if(/growth|marketing|content|community|social|seo|creator|producer|writer/.test(s))return'Marketing / Community';if(/ai operations|ai trainer|annotation|localization|translation/.test(s))return'AI / Evaluation';return'Other'}
function seniority(role=''){const s=role.toLowerCase();if(/intern/.test(s))return'Intern';if(/lead|head|director|chief/.test(s))return'Lead';if(/manager/.test(s))return'Manager';if(/senior|enterprise/.test(s))return'Senior';if(/junior|entry|associate|assistant|specialist|representative|coordinator|agent/.test(s))return'Junior';return'Mid'}
function salaryProfile(role='',cat='Other',sen='Mid'){const s=role.toLowerCase();let min=24000,max=38000,confidence='Medium',note='Market estimate';let variable='';
 if(/customer success engineer|support engineer/.test(s)){min=42000;max=68000}
 else if(/technical support/.test(s)){min=26000;max=44000}
 else if(/customer success manager/.test(s)){min=32000;max=54000}
 else if(/customer success lead|head of customer success/.test(s)){min=48000;max=76000}
 else if(/customer support|customer service|community support/.test(s)){min=22000;max=36000}
 else if(/revenue operations/.test(s)){min=36000;max=58000}
 else if(/operations/.test(s)){min=24000;max=40000}
 else if(/qa tester|quality assurance|\bqa\b/.test(s)){min=25000;max=42000}
 else if(/account executive/.test(s)){min=36000;max=58000;variable='OTE ~€50k–€85k'}
 else if(/sales development|\bsdr\b|business development representative/.test(s)){min=25000;max=40000;variable='OTE ~€32k–€55k'}
 else if(/sales executive|b2b business development/.test(s)){min=30000;max=48000;variable='OTE ~€40k–€70k'}
 else if(/growth marketing manager|growth manager|marketing lead/.test(s)){min=36000;max=60000}
 else if(/content marketing manager|social media marketing manager|social media manager|community manager|content strategist|seo/.test(s)){min=27000;max=47000}
 else if(/content writer|creative producer/.test(s)){min=24000;max=40000}
 else if(/trust|moderator|safety/.test(s)){min=22000;max=36000}
 else if(/ai operations|ai trainer|annotation|localization|translation/.test(s)){min=24000;max=42000}
 else if(/technical assistant/.test(s)){min=24000;max=40000}
 if(/open application|unsolicited|open introduction/.test(s)){min=Math.max(22000,min-3000);max=Math.max(min+8000,max-4000);confidence='Low'}
 if(sen==='Intern'){min=Math.min(min,14000);max=Math.min(max,24000);confidence='Medium'}
 if(sen==='Lead'){min=Math.round(min*1.2);max=Math.round(max*1.25)}
 if(sen==='Senior'){min=Math.round(min*1.12);max=Math.round(max*1.18)}
 return{min,max,mid:(min+max)/2,monthlyMin:min/12,monthlyMax:max/12,confidence,note,variable}}
function duties(role='',cat='Other'){const s=role.toLowerCase();if(/account executive/.test(s))return['Run demos and sales calls','Build pipeline and close deals','Manage CRM, follow-ups and forecasts'];if(/sdr|sales development/.test(s))return['Find and qualify prospects','Cold email/call and book meetings','Track outreach and pipeline in CRM'];if(/business development|sales executive/.test(s))return['Find new customers/partners','Pitch offers and negotiate','Own follow-ups and revenue targets'];if(/customer success engineer/.test(s))return['Solve technical customer issues','Guide integrations/API usage','Work with engineering on escalations'];if(/customer success/.test(s))return['Onboard and support customers','Run check-ins and solve account issues','Improve retention, adoption and renewals'];if(/technical support|helpdesk|technical assistant/.test(s))return['Diagnose software/hardware issues','Handle tickets and user troubleshooting','Document fixes and escalate harder cases'];if(/customer support|customer service|community support/.test(s))return['Answer customer questions','Resolve tickets/orders/account issues','Keep response quality and satisfaction high'];if(/revenue operations/.test(s))return['Maintain CRM and sales data','Build reports and clean workflows','Support forecasting and process automation'];if(/operations|fulfilment/.test(s))return['Run day-to-day workflows','Track orders/data/tasks and exceptions','Coordinate teams and improve process accuracy'];if(/qa|tester|quality assurance/.test(s))return['Test product flows and edge cases','Log reproducible bugs','Retest fixes and maintain test cases'];if(/trust|moderator|safety/.test(s))return['Review content/accounts for policy issues','Handle escalations and abuse reports','Document decisions consistently'];if(/growth marketing|growth manager/.test(s))return['Run acquisition experiments','Track funnel and campaign metrics','Improve conversion and growth channels'];if(/content marketing/.test(s))return['Plan and publish content','Write/edit campaigns and landing pages','Measure traffic, leads and engagement'];if(/community|social media/.test(s))return['Run social/community channels','Create posts and respond to users','Track engagement and grow audience'];if(/seo|content strategist/.test(s))return['Research keywords and topics','Plan SEO/content roadmap','Measure rankings, traffic and conversions'];if(/writer/.test(s))return['Research and write content','Edit for brand/SEO quality','Manage publishing deadlines'];if(/ai operations|ai trainer|annotation/.test(s))return['Review/label AI data or outputs','Follow quality rubrics precisely','Flag edge cases and improve workflows'];return['Handle the core workflow implied by the role','Coordinate with customers or internal teams','Track work, issues and outcomes in company tools']}
function cvReasons(cat,role=''){if(cat==='Technical Support')return['ERT remote/network troubleshooting','iRED hardware/software diagnosis','INSPOT customer + computer support'];if(cat==='Customer Success / Support')return['Strong customer-facing history','Technical troubleshooting background','Native Greek + C2 English'];if(cat==='Operations / Data')return['ALUMINCO SAP/order/inventory operations','Process accuracy and fulfillment work','Technical systems comfort'];if(cat==='Sales / BD')return['COSMOTE lead generation/promotion','PR and prospect communication','Customer-facing confidence'];if(cat==='Marketing / Community')return['ELLI digital presence/communications','PR + social/event promotion','Customer/community communication'];if(cat==='QA / Testing')return['Troubleshooting mindset','Hardware/software diagnosis','Strong process/detail orientation'];if(cat==='Trust & Safety')return['Support + escalation experience','Process consistency','Communication under pressure'];if(cat==='AI / Evaluation')return['Technical education','Ops/detail orientation','Strong English + digital systems experience'];return['Broad technical + customer background','Operations experience','Fast learner across systems']}
function score(role='',cat='Other',sen='Mid',pay={mid:30000}){let fit=6.7,ease=6.7;if(cat==='Technical Support'){fit=8.9;ease=8.0}else if(cat==='Customer Success / Support'){fit=8.5;ease=7.8}else if(cat==='Operations / Data'){fit=8.7;ease=8.2}else if(cat==='QA / Testing'){fit=8.2;ease=7.6}else if(cat==='Trust & Safety'){fit=7.8;ease=7.7}else if(cat==='Marketing / Community'){fit=7.4;ease=7.0}else if(cat==='Sales / BD'){fit=7.0;ease=6.5}else if(cat==='AI / Evaluation'){fit=7.6;ease=7.3}if(sen==='Lead'){ease-=1.5;fit-=.5}else if(sen==='Manager'){ease-=1}else if(sen==='Senior'){ease-=1.2}else if(sen==='Junior'){ease+=.5}else if(sen==='Intern'){ease+=.8}if(/open application|unsolicited/.test(role.toLowerCase()))ease-=.2;fit=clamp(fit);ease=clamp(ease);const traction=clamp(fit*.56+ease*.44-.35);let prestige=5.3,future=3.8;const j=role.toLowerCase();if(/ai|api|technical|software|fintech|automation/.test(j))future=7.2;if(/ai operations|customer success engineer/.test(j))future=8.2;const payScore=clamp(3+(pay.mid-18000)/7000);const overall=(fit*.28+traction*.24+ease*.18+prestige*.08+future*.08+payScore*.14)*10;const action=overall>=76&&ease>=7?'GO':overall>=65?'MAYBE':'STRETCH';return{fit,ease,traction,prestige,future,payScore,overall,action,tier:overall>=80?'S':overall>=72?'A':overall>=63?'B':'C'}}
function enrich(x){const cat=classify(x.role),sen=seniority(x.role),pay=salaryProfile(x.role,cat,sen),sc=score(x.role,cat,sen,pay);return{...x,category:cat,seniority:sen,pay,duties:duties(x.role,cat),cvReasons:cvReasons(cat,x.role),...sc}}
function clamp(n){return Math.max(1,Math.min(10,n))}
function filtered(){const q=$('#search').value.toLowerCase();return DATA.filter(a=>(FILTER==='all'||a.category===FILTER||(FILTER==='go'&&a.action==='GO')||(FILTER==='highpay'&&a.pay.mid>=45000))&&(!q||(a.company+' '+a.role+' '+a.category+' '+a.duties.join(' ')).toLowerCase().includes(q))).sort((a,b)=>b.overall-a.overall)}
function meter(v){return `<div class="meter"><i style="width:${Math.round(v*10)}%"></i><b>${v.toFixed(1)}</b></div>`}
function render(){const rows=filtered(),uniq=new Set(DATA.map(a=>(a.company+'|'+a.role).toLowerCase())).size,companies=new Set(DATA.map(a=>a.company.toLowerCase())).size,avg=k=>(DATA.reduce((s,a)=>s+a[k],0)/DATA.length).toFixed(1),avgPay=Math.round(DATA.reduce((s,a)=>s+a.pay.mid,0)/DATA.length);$('#subtitle').textContent=`${DATA.length} Gmail Sent records · ${uniq} unique company-role pairs · ${companies} companies · pay shown as gross annual EUR`;
 $('#kpis').innerHTML=[['Sent',DATA.length],['Unique apps',uniq],['Companies',companies],['GO now',DATA.filter(a=>a.action==='GO').length],['Avg fit',avg('fit')],['Avg ease',avg('ease')],['Avg market pay',eur(avgPay)],['€45k+ est.',DATA.filter(a=>a.pay.mid>=45000).length]].map(([l,v])=>`<div class=kpi><span>${l}</span><strong>${v}</strong></div>`).join('');
 const best=[...DATA].sort((a,b)=>b.overall-a.overall)[0],money=[...DATA].sort((a,b)=>b.pay.mid-a.pay.mid)[0],easy=[...DATA].sort((a,b)=>b.ease-a.ease)[0],tech=[...DATA].sort((a,b)=>b.future-a.future||b.overall-a.overall)[0];$('#heroCards').innerHTML=[[best,'BEST OVERALL'],[money,'BEST PAY'],[easy,'EASIEST FIT'],[tech,'FUTURE TECH']].map(([a,t])=>`<div class="heroCard"><span>${t}</span><strong>${esc(a.company)}</strong><p>${esc(a.role)}</p><div><b>${Math.round(a.overall)}/100</b><b>${eur(a.pay.min)}–${eur(a.pay.max)}</b></div></div>`).join('');
 const cats=['all','go','highpay',...new Set(DATA.map(a=>a.category))];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${FILTER===c?'active':''}" data-f="${c}">${c==='all'?'All 300':c==='go'?'GO now':c==='highpay'?'€45k+ est.':c}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{FILTER=b.dataset.f;render()});$('#countLabel').textContent=`${rows.length} applications shown`;
 $('#tbody').innerHTML=rows.map((a,i)=>`<tr data-id="${a.gmailMessageId}"><td class=num>${i+1}</td><td><div class=company>${esc(a.company)}</div><div class=role>${esc(a.role)}</div><div class=minitags><span>${a.category}</span><span>${a.seniority}</span></div></td><td><div class=task>${esc(a.duties[0])}</div><div class=tasksub>${esc(a.duties[1])}</div></td><td><div class=pay>${eur(a.pay.min)}–${eur(a.pay.max)}</div><div class=tasksub>€${Math.round(a.pay.monthlyMin).toLocaleString()}–€${Math.round(a.pay.monthlyMax).toLocaleString()}/mo gross</div>${a.pay.variable?`<div class=ote>${a.pay.variable}</div>`:''}<div class=estimate>Market estimate · ${a.pay.confidence}</div></td><td>${meter(a.fit)}</td><td>${meter(a.ease)}</td><td>${meter(a.traction)}</td><td class="num overall">${Math.round(a.overall)}</td><td><span class="action ${a.action.toLowerCase()}">${a.action}</span></td></tr>`).join('');document.querySelectorAll('#tbody tr').forEach(r=>r.onclick=()=>showDetail(DATA.find(a=>a.gmailMessageId===r.dataset.id)));renderCats();renderPay();renderBets();drawScatter(rows)}
function renderCats(){const m={};DATA.forEach(a=>m[a.category]=(m[a.category]||0)+1);const max=Math.max(...Object.values(m));$('#categoryBars').innerHTML=Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class=barrow><span>${k}</span><div class=bartrack><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')}
function renderPay(){const bins=[['<€30k',a=>a.pay.mid<30000],['€30–40k',a=>a.pay.mid>=30000&&a.pay.mid<40000],['€40–50k',a=>a.pay.mid>=40000&&a.pay.mid<50000],['€50k+',a=>a.pay.mid>=50000]],max=Math.max(...bins.map(x=>DATA.filter(x[1]).length));$('#payBars').innerHTML=bins.map(([k,f])=>{const v=DATA.filter(f).length;return `<div class=barrow><span>${k}</span><div class=bartrack><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`}).join('')}
function renderBets(){const top=[...DATA].filter(a=>a.action!=='STRETCH').sort((a,b)=>b.overall-a.overall).slice(0,7);$('#topBets').innerHTML=top.map(a=>`<div class=bet><strong>${esc(a.company)}</strong><span>${esc(a.role)}</span><div class=scoreline><b>${Math.round(a.overall)}/100</b><b>FIT ${a.fit.toFixed(1)}</b><b>${eur(a.pay.min)}–${eur(a.pay.max)}</b><i class="action ${a.action.toLowerCase()}">${a.action}</i></div></div>`).join('')}
function drawScatter(rows){const c=$('#scatter'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=36,mins=Math.min(...DATA.map(a=>a.pay.mid)),maxs=Math.max(...DATA.map(a=>a.pay.mid));ctx.clearRect(0,0,w,h);ctx.strokeStyle='#17303b';ctx.font='11px monospace';for(let i=0;i<5;i++){const y=p+i*(h-2*p)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}rows.forEach(a=>{const x=p+(a.ease-1)*(w-2*p)/9,y=h-p-(a.pay.mid-mins)/(maxs-mins||1)*(h-2*p);ctx.fillStyle=a.action==='GO'?'#6be7adbb':a.action==='MAYBE'?'#ffc66daa':'#ff7d86aa';ctx.beginPath();ctx.arc(x,y,3+(a.fit/10)*2,0,Math.PI*2);ctx.fill()})}
function showDetail(a){if(!a)return;$('#detailBody').innerHTML=`<div class=eyebrow>${a.category} · ${a.seniority}</div><h1>${esc(a.company)}</h1><p class=detailrole>${esc(a.role)}</p><div class=decisionStrip><span class="action ${a.action.toLowerCase()}">${a.action}</span><strong>${Math.round(a.overall)}/100 overall</strong><strong>${eur(a.pay.min)}–${eur(a.pay.max)} / yr</strong></div><section class=detailSection><h3>What you would actually do</h3>${a.duties.map(x=>`<div class=duty>✓ ${esc(x)}</div>`).join('')}</section><section class=detailSection><h3>Expected compensation</h3><div class=bigpay>${eur(a.pay.min)}–${eur(a.pay.max)} gross/year</div><p>≈ €${Math.round(a.pay.monthlyMin).toLocaleString()}–€${Math.round(a.pay.monthlyMax).toLocaleString()} gross/month. <b>${a.pay.note}</b> · confidence ${a.pay.confidence}.${a.pay.variable?' '+a.pay.variable+'.':''}</p></section><section class=detailSection><h3>Why your CV fits</h3>${a.cvReasons.map(x=>`<div class=duty>• ${esc(x)}</div>`).join('')}</section><div class=detailScores>${[['Fit',a.fit],['Ease',a.ease],['Traction',a.traction],['Pay',a.payScore],['Future',a.future],['Overall',a.overall/10]].map(([l,v])=>`<div class=detailScore><span>${l}</span><b>${v.toFixed(1)}</b></div>`).join('')}</div><div class=meta><b>Interpretation:</b> GO = strong combination of CV fit, accessibility and compensation. MAYBE = worth keeping, but has a meaningful gap. STRETCH = seniority/role mismatch or weaker accessibility.<br><br><b>Important:</b> Traction is a heuristic, not an interview probability. Pay is a market estimate unless a future data enrichment marks it employer-disclosed.<br><b>Gmail record:</b> ${a.gmailMessageId}</div>`;$('#detail').showModal()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exportCsv(){const rows=filtered(),cols=['company','role','category','seniority','marketPayMin','marketPayMax','fit','ease','traction','overall','action','gmailMessageId'];const out=[cols.join(','),...rows.map(a=>[a.company,a.role,a.category,a.seniority,a.pay.min,a.pay.max,a.fit,a.ease,a.traction,a.overall,a.action,a.gmailMessageId].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\n');const u=URL.createObjectURL(new Blob([out],{type:'text/csv'})),x=document.createElement('a');x.href=u;x.download='application-command-center-enriched.csv';x.click();URL.revokeObjectURL(u)}
$('#unlock').onclick=unlock;$('#pass').onkeydown=e=>{if(e.key==='Enter')unlock()};$('#search').oninput=render;$('#closeDetail').onclick=()=>$('#detail').close();$('#lockBtn').onclick=()=>location.reload();$('#exportBtn').onclick=exportCsv;